package jp.rimtty.codematch.history

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.SnackbarResult
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import jp.rimtty.codematch.R
import jp.rimtty.codematch.core.model.AppLanguage
import jp.rimtty.codematch.core.model.MatchSession
import jp.rimtty.codematch.feature.history.HistoryContent
import jp.rimtty.codematch.feature.history.HistoryLayoutMode
import jp.rimtty.codematch.navigation.CodeMatchBackHandler
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Application-owned history destination.
 *
 * Persistence and navigation state are kept here while the feature module
 * remains a reusable stateless Compose surface. The caller's Activity owns the
 * surrounding scaffold; this route only supplies the content and Android
 * document/share bridges.
 */
@Composable
fun HistoryRoute(modifier: Modifier = Modifier) {
    val viewModel: HistoryViewModel = hiltViewModel()
    val state by viewModel.state.collectAsStateWithLifecycle()
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val snackbarHostState = remember { SnackbarHostState() }
    var feedback by remember { mutableStateOf<HistoryPdfFeedback?>(null) }

    // IDs are saveable so a compact detail remains selected after Activity
    // recreation. CodeMatchApp additionally keeps this destination's state
    // while the user switches between top-level destinations.
    var selectedSessionId by rememberSaveable { mutableStateOf<String?>(null) }
    var selectedGroupCode by rememberSaveable { mutableStateOf<String?>(null) }
    var selectedEntryId by rememberSaveable { mutableStateOf<String?>(null) }
    var pendingDocument by remember { mutableStateOf<PendingHistoryPdf?>(null) }
    // Keep only the session ID across recreation. The generated bytes are
    // intentionally not persisted; an interrupted picker flow is regenerated
    // from the current Room session when the user retries.
    var latestSaveSessionId by rememberSaveable { mutableStateOf<String?>(null) }
    var exportGeneration by remember { mutableStateOf(0L) }
    var launchSavePicker: ((PendingHistoryPdf) -> Unit)? = null

    val retryLabel = androidx.compose.ui.res.stringResource(R.string.history_pdf_retry)
    val saveErrorMessage = androidx.compose.ui.res.stringResource(R.string.history_pdf_save_error)
    val shareErrorMessage = androidx.compose.ui.res.stringResource(R.string.history_pdf_share_error)

    fun reportPdfFailure(message: String, retry: (() -> Unit)?) {
        feedback = HistoryPdfFeedback(message = message, retry = retry)
    }

    fun startSave(session: MatchSession) {
        feedback = null
        latestSaveSessionId = session.id
        val generation = exportGeneration + 1L
        exportGeneration = generation
        pendingDocument = null
        preparePdfForSave(
            session = session,
            language = state.language,
            scope = scope,
        ) { result ->
            if (generation != exportGeneration) return@preparePdfForSave
            when (result) {
                is HistoryPdfResult.Success -> {
                    val launch = launchSavePicker
                    if (launch == null) {
                        reportPdfFailure(saveErrorMessage) { startSave(session) }
                    } else {
                        launch(result.value)
                    }
                }
                is HistoryPdfResult.Failure -> {
                    reportPdfFailure(saveErrorMessage) { startSave(session) }
                }
            }
        }
    }

    fun startShare(session: MatchSession) {
        feedback = null
        val generation = exportGeneration + 1L
        exportGeneration = generation
        pendingDocument = null
        preparePdfForShare(
            context = context,
            session = session,
            language = state.language,
            scope = scope,
        ) { result ->
            if (generation != exportGeneration) return@preparePdfForShare
            when (result) {
                is HistoryPdfResult.Success -> {
                    when (HistoryPdfBridge.launchShare(context, result.value)) {
                        is HistoryPdfResult.Success -> Unit
                        is HistoryPdfResult.Failure -> {
                            reportPdfFailure(shareErrorMessage) { startShare(session) }
                        }
                    }
                }
                is HistoryPdfResult.Failure -> {
                    reportPdfFailure(shareErrorMessage) { startShare(session) }
                }
            }
        }
    }

    fun handleDocumentResult(destination: Uri?) {
        val pending = pendingDocument
        pendingDocument = null
        when (val pickerResult = HistoryPdfBridge.resolveDocumentPickerResult(destination, pending)) {
            HistoryPdfPickerResult.Cancelled -> {
                // User cancellation is an intentional end of the flow, not an error.
            }
            HistoryPdfPickerResult.MissingPendingDocument -> {
                val retrySession = state.sessions.firstOrNull { it.id == latestSaveSessionId }
                reportPdfFailure(saveErrorMessage, retrySession?.let { session -> { startSave(session) } })
            }
            is HistoryPdfPickerResult.Selected -> {
                val generation = exportGeneration
                scope.launch(Dispatchers.IO) {
                    val result = HistoryPdfBridge.writeDocument(
                        context.contentResolver,
                        pickerResult.destination,
                        pickerResult.document,
                    )
                    withContext(Dispatchers.Main.immediate) {
                        if (generation != exportGeneration) return@withContext
                        when (result) {
                            is HistoryPdfResult.Success -> Unit
                            is HistoryPdfResult.Failure -> {
                                reportPdfFailure(saveErrorMessage) {
                                    launchSavePicker?.invoke(pickerResult.document)
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    val createDocument = rememberLauncherForActivityResult(
        contract = HistoryPdfBridge.createDocumentContract(),
    ) { destination -> handleDocumentResult(destination) }
    launchSavePicker = { pending ->
        pendingDocument = pending
        when (HistoryPdfBridge.launchDocumentPicker(createDocument::launch, pending.fileName)) {
            is HistoryPdfResult.Success -> Unit
            is HistoryPdfResult.Failure -> {
                pendingDocument = null
                val retrySession = state.sessions.firstOrNull { it.id == latestSaveSessionId }
                reportPdfFailure(saveErrorMessage, retrySession?.let { session -> { startSave(session) } })
            }
        }
    }

    // A deleted session should not leave a stale detail pane selected. This
    // also handles Room's first emission after process recreation.
    val selectedSessionExists = state.sessions.any { it.id == selectedSessionId }
    LaunchedEffect(selectedSessionId, selectedSessionExists, state.loaded) {
        // Do not clear a restored ID while Room is still on the ViewModel's
        // empty initial value. Once the first repository emission arrives,
        // a genuinely deleted/stale session is safe to clear.
        if (state.loaded && selectedSessionId != null && !selectedSessionExists) {
            selectedSessionId = null
            selectedGroupCode = null
            selectedEntryId = null
        }
    }

    Box(modifier = modifier.fillMaxSize().statusBarsPadding()) {
        BoxWithConstraints(Modifier.fillMaxSize()) {
            val layoutMode = if (maxWidth >= EXPANDED_MIN_WIDTH) {
                HistoryLayoutMode.EXPANDED
            } else {
                HistoryLayoutMode.COMPACT
            }
            val selection = HistoryNavigationSelection(
                sessionId = selectedSessionId,
                groupCode = selectedGroupCode,
                entryId = selectedEntryId,
            )
            val goBack: () -> Unit = {
                val previous = HistoryNavigationSelection(
                    sessionId = selectedSessionId,
                    groupCode = selectedGroupCode,
                    entryId = selectedEntryId,
                ).pop()
                selectedSessionId = previous.sessionId
                selectedGroupCode = previous.groupCode
                selectedEntryId = previous.entryId
            }

            CodeMatchBackHandler(
                enabled = selection.canNavigateBack(layoutMode),
                onBack = goBack,
            )

            HistoryContent(
                sessions = state.sessions,
                selectedSessionId = selectedSessionId,
                layoutMode = layoutMode,
                selectedGroupCode = selectedGroupCode,
                selectedEntryId = selectedEntryId,
                language = state.language,
                onSessionSelected = { sessionId ->
                    selectedSessionId = sessionId
                    selectedGroupCode = null
                    selectedEntryId = null
                },
                onDeleteSession = { sessionId ->
                    if (selectedSessionId == sessionId) {
                        selectedSessionId = null
                        selectedGroupCode = null
                        selectedEntryId = null
                    }
                    viewModel.deleteSession(sessionId)
                },
                onRenameSession = viewModel::renameSession,
                onGroupSelected = { code ->
                    selectedGroupCode = code
                    selectedEntryId = null
                },
                onEntrySelected = { entryId -> selectedEntryId = entryId },
                onBack = goBack,
                onSavePdf = ::startSave,
                onSharePdf = ::startShare,
                modifier = Modifier.fillMaxSize(),
            )
        }
        HistoryPdfFeedbackHost(
            snackbarHostState = snackbarHostState,
            feedback = feedback,
            retryLabel = retryLabel,
            onConsumed = { feedback = null },
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .padding(horizontal = 16.dp, vertical = 8.dp),
        )
    }
}

/**
 * The compact history destination behaves like a list/detail back stack.
 * Expanded layouts keep the list visible, so only nested group/box details
 * consume system back there.
 */
internal data class HistoryNavigationSelection(
    val sessionId: String? = null,
    val groupCode: String? = null,
    val entryId: String? = null,
) {
    fun canNavigateBack(layoutMode: HistoryLayoutMode): Boolean = when (layoutMode) {
        HistoryLayoutMode.COMPACT -> sessionId != null || groupCode != null || entryId != null
        HistoryLayoutMode.EXPANDED -> groupCode != null || entryId != null
    }

    fun pop(): HistoryNavigationSelection = when {
        entryId != null -> copy(entryId = null)
        groupCode != null -> copy(groupCode = null)
        sessionId != null -> copy(sessionId = null)
        else -> this
    }
}

internal data class HistoryPdfFeedback(
    val message: String,
    val retry: (() -> Unit)?,
)

internal object HistoryPdfTestTags {
    const val FEEDBACK = "historyPdfFeedback"
}

/**
 * Accessible, localized feedback surface for export failures. The route owns
 * the strings and retry callback; this composable only coordinates the
 * snackbar action and deliberately renders no technical failure details.
 */
@Composable
internal fun HistoryPdfFeedbackHost(
    snackbarHostState: SnackbarHostState,
    feedback: HistoryPdfFeedback?,
    retryLabel: String,
    onConsumed: () -> Unit,
    modifier: Modifier = Modifier,
) {
    SnackbarHost(
        hostState = snackbarHostState,
        modifier = modifier.testTag(HistoryPdfTestTags.FEEDBACK),
    )
    LaunchedEffect(feedback) {
        val current = feedback ?: return@LaunchedEffect
        val result = snackbarHostState.showSnackbar(
            message = current.message,
            actionLabel = current.retry?.let { retryLabel },
            withDismissAction = true,
        )
        if (result == SnackbarResult.ActionPerformed) {
            current.retry?.invoke()
        }
        onConsumed()
    }
}

private fun preparePdfForSave(
    session: MatchSession,
    language: AppLanguage,
    scope: kotlinx.coroutines.CoroutineScope,
    onResult: (HistoryPdfResult<PendingHistoryPdf>) -> Unit,
) {
    scope.launch(Dispatchers.IO) {
        val result = HistoryPdfBridge.createDocument(session, language)
        withContext(Dispatchers.Main.immediate) { onResult(result) }
    }
}

private fun preparePdfForShare(
    context: Context,
    session: MatchSession,
    language: AppLanguage,
    scope: kotlinx.coroutines.CoroutineScope,
    onResult: (HistoryPdfResult<Intent>) -> Unit,
) {
    scope.launch(Dispatchers.IO) {
        val result = when (val cacheResult = HistoryPdfBridge.writeShareCache(context, session, language)) {
            is HistoryPdfResult.Success -> HistoryPdfBridge.createShareChooser(context, cacheResult.value)
            is HistoryPdfResult.Failure -> HistoryPdfResult.Failure(cacheResult.reason)
        }
        withContext(Dispatchers.Main.immediate) {
            onResult(result)
        }
    }
}

private val EXPANDED_MIN_WIDTH = 840.dp
