package jp.rimtty.codematch.core.export

import jp.rimtty.codematch.core.model.AppLanguage
import jp.rimtty.codematch.core.model.Destination
import jp.rimtty.codematch.core.model.MatchEntry
import jp.rimtty.codematch.core.model.MatchSession
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class HistoryPdfContentTest {
    private val qrPayload =
        "DCLP675300BCJH5281GG020000120000001200L000000000000BLBDILLU92   0*"
    private val barcodePayload = "BCJH-52-81GG@1N5X0C"

    // Trailing spaces are part of the fixed-position Molten record; the length
    // assertions below fail first if an editor ever trims them away.
    private val moltenQr1 =
        "AK6805D10E50N10B         U543820000MB    S600700000020908    "
    private val moltenQr2 =
        "AK6805PAF115422          UAG5560000FA2P5901FEM000012009080000"

    // Real デンソー kanbans; see shared/test-fixtures/matching-cases.json. The
    // runs of spaces inside are blank fixed-width fields and are data.
    private val densoQr0140 = "JAMA501195000001021100021041011102112071210412406127041410214201144061520440205515015160151908520045210652606523105220640102208601507722000000024D850C01008D85045M      0140SWS    20260908S0010000720000009924543330454333M6"
    private val densoQr0141 = "JAMA501195000001021100021041011102112071210412406127041410214201144061520440205515015160151908520045210652606523105220640102208601507722000000024D850C01008D85045M      0141SWS    20260908S0010000720000009924543330454333M6"
    private val densoQr0538 = "JAMA501195000001021100021041011102112071210412406127041410214201144061520440205515015160151908520045210652606523105220640102208601507791000000192D860C01008D86045M      0538SWS    20260908S0010007680000009924543420454342R6"

    @Test
    fun contentPreservesFirstSeenGroupsParsedFieldsManagementAndRawPayloads() {
        val session = MatchSession(
            startedAt = 1_700_000_000_000L,
            endedAt = 1_700_000_120_000L,
            name = "Morning run",
            entries = listOf(
                MatchEntry(
                    id = "one",
                    code = "BCJH-52-81GG",
                    matchedAt = 1_700_000_001_000L,
                    qrPayload = qrPayload,
                    barcodePayload = barcodePayload,
                    sequence = 0,
                ),
                MatchEntry(
                    id = "two",
                    code = "BCJH-52-81GG",
                    matchedAt = 1_700_000_002_000L,
                    qrPayload = null,
                    barcodePayload = null,
                    sequence = 1,
                ),
                MatchEntry(
                    id = "three",
                    code = "KAAA-55-D86B",
                    matchedAt = 1_700_000_003_000L,
                    qrPayload = "legacy KAAA payload",
                    barcodePayload = "KAAA-55-D86B@management-2",
                    sequence = 2,
                ),
            ),
        )

        val blocks = HistoryPdfContent.build(session, AppLanguage.JAPANESE)
        val text = blocks.joinToString("\n") { it.text }
        val firstGroup = text.indexOf("#1 BCJH-52-81GG")
        val secondGroup = text.indexOf("#2 KAAA-55-D86B")

        assertTrue(text.contains("Morning run"))
        assertTrue(text.contains("検査箱数: 3箱（品番数: 2）"))
        assertTrue(firstGroup >= 0)
        assertTrue(secondGroup > firstGroup)
        assertTrue(text.contains("納品書情報"))
        assertTrue(text.contains("カード番号: DCLP675300"))
        assertTrue(text.contains("品目番号: BCJH-52-81GG"))
        assertTrue(text.contains("管理コード: 1N5X0C"))
        assertTrue(text.contains("QR全文: $qrPayload"))
        assertTrue(text.contains("Code 128全文: $barcodePayload"))
        assertTrue(text.contains("記録なし（旧バージョンで照合）"))
        assertTrue(text.contains("management-2"))
        assertTrue(text.contains("端末内のデータから作成されています"))
    }

    @Test
    fun englishContentUsesEnglishLabelsAndIncludesEmptySessionMessage() {
        val session = MatchSession(startedAt = 0L, endedAt = 1_000L)

        val text = HistoryPdfContent.build(session, AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Match History Report"))
        assertTrue(text.contains("Boxes: 0 boxes (part numbers: 0)"))
        assertTrue(text.contains("There are no matched codes."))
        assertTrue(text.contains("Generated by CodeMatch"))
    }

    @Test
    fun englishContentInflectsBoxUnitForOneAndMany() {
        val session = MatchSession(
            endedAt = 2_000L,
            entries = listOf(
                MatchEntry(id = "one", code = "ONE"),
                MatchEntry(id = "two", code = "TWO"),
                MatchEntry(id = "three", code = "TWO"),
            ),
        )

        val text = HistoryPdfContent.build(session, AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Boxes: 3 boxes (part numbers: 2)"))
        assertTrue(text.contains("#1 ONE (1 box)"))
        assertTrue(text.contains("#2 TWO (2 boxes)"))
    }

    @Test
    fun moltenReportGroupsBoxesPerDeliveryNumberWithCumulativeQuantityAndAllFields() {
        assertEquals(61, moltenQr1.length)
        assertEquals(61, moltenQr2.length)

        val text = HistoryPdfContent.build(moltenSession(), AppLanguage.JAPANESE)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("仕向地: モルテン"))
        assertTrue(text.contains("検査箱数: 3箱（品番数: 2）"))
        assertTrue(text.contains("納品番号数: 2"))
        assertTrue(text.contains("#1 PAF1-15-422 (2箱)"))
        assertTrue(text.contains("納品番号: UAG5560（2箱、累計 240 個）"))
        assertTrue(text.contains("部品番号: PAF1-15-422; 受注者: AK6805"))
        assertTrue(text.contains("納入先: FA2; TYロケーション: P59; 供給先: 01FEM"))
        assertTrue(text.contains("納入指示日(JUMP): 09/08; 時刻: 00:00"))
        assertTrue(text.contains("収容数: 120; 管理コード: 0NKD3C"))
        assertTrue(text.contains("収容数: 120; 管理コード: 0NLL3C"))
        assertTrue(text.contains("#2 D10E-50-N10B (1箱)"))
        assertTrue(text.contains("納品番号: U543820（1箱、累計 2 個）"))
        assertTrue(text.contains("納入先: MB; TYロケーション: -; 供給先: S6007"))
        assertTrue(text.contains("納入指示日(JUMP): 09/08; 時刻: -"))
        assertTrue(text.contains("収容数: 2; 管理コード: 0UBL00"))
        assertTrue(text.contains("QR全文: $moltenQr1"))
        assertTrue(text.contains("QR全文: $moltenQr2"))
    }

    @Test
    fun englishMoltenReportUsesEnglishLabels() {
        val text = HistoryPdfContent.build(moltenSession(), AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Ship-to: Molten"))
        assertTrue(text.contains("Delivery numbers: 2"))
        assertTrue(text.contains("Delivery number: UAG5560 (2 boxes, Total 240 pcs)"))
        assertTrue(text.contains("Delivery number: U543820 (1 box, Total 2 pcs)"))
        assertTrue(text.contains("Part number: PAF1-15-422; Orderer: AK6805"))
        assertTrue(text.contains("Delivery point: FA2; TY location: P59; Supply point: 01FEM"))
        assertTrue(text.contains("Instruction date (JUMP): 09/08; Time: 00:00"))
        assertTrue(text.contains("Instruction date (JUMP): 09/08; Time: -"))
        assertTrue(text.contains("Pack quantity: 120; Management code: 0NKD3C"))
    }

    @Test
    fun legacySawaiReportIsUnchangedWhenDestinationIsNull() {
        val session = MatchSession(
            startedAt = 1_700_000_000_000L,
            endedAt = 1_700_000_120_000L,
            destination = null,
            entries = listOf(
                MatchEntry(
                    id = "one",
                    code = "BCJH-52-81GG",
                    matchedAt = 1_700_000_001_000L,
                    qrPayload = qrPayload,
                    barcodePayload = barcodePayload,
                    sequence = 0,
                ),
            ),
        )

        val text = HistoryPdfContent.build(session, AppLanguage.JAPANESE)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("検査箱数: 1箱（品番数: 1）"))
        assertTrue(text.contains("#1 BCJH-52-81GG (1箱)"))
        assertTrue(text.contains("納品書情報"))
        assertTrue(text.contains("品目番号: BCJH-52-81GG"))
        assertTrue(text.contains("カード番号: DCLP675300"))
        assertTrue(text.contains("管理コード: 1N5X0C"))
        assertTrue(text.contains("QR全文: $qrPayload"))
        assertTrue(text.contains("Code 128全文: $barcodePayload"))
        // The Molten delivery block must never leak into a Sawai report.
        assertFalse(text.contains("納品番号"))
        assertFalse(text.contains("収容数"))
        // A legacy session stores no destination, so the label is derived from
        // the recorded QR instead.
        assertTrue(text.contains("仕向地: 澤井製作所"))

        val unresolved = MatchSession(entries = listOf(MatchEntry(id = "legacy", code = "LEGACY")))
        val unresolvedText = HistoryPdfContent.build(unresolved, AppLanguage.JAPANESE)
            .joinToString("\n") { it.text }

        assertFalse(unresolvedText.contains("仕向地:"))
    }

    @Test
    fun densoReportPrintsKanbanBlockAndBoxesPerPartNumber() {
        assertEquals(221, densoQr0140.length)
        assertEquals(221, densoQr0141.length)
        assertEquals(221, densoQr0538.length)

        val text = HistoryPdfContent.build(densoSession(), AppLanguage.JAPANESE)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("仕向地: デンソー"))
        assertTrue(text.contains("検査箱数: 3箱（品番数: 2）"))
        assertTrue(text.contains("#1 860150-7722 (2箱)"))
        assertTrue(text.contains("部品番号: 860150-7722; 収容数: 24; 指示数: 72"))
        assertTrue(text.contains("次区: D850; 指示: C01008-45; 納入日: 2026/09/08; 便: S001"))
        assertTrue(text.contains("管理番号: SWS; アイテムNo: 9924543330; 受入: M6"))
        // The kanban serial is what separates two boxes of the same part.
        assertTrue(text.contains("かんばん連番: 0140; 管理コード: 1DZ50O"))
        assertTrue(text.contains("かんばん連番: 0141; 管理コード: 1DZB0O"))
        assertTrue(text.contains("#2 860150-7791 (1箱)"))
        assertTrue(text.contains("部品番号: 860150-7791; 収容数: 192; 指示数: 768"))
        assertTrue(text.contains("次区: D860; 指示: C01008-45; 納入日: 2026/09/08; 便: S001"))
        assertTrue(text.contains("管理番号: SWS; アイテムNo: 9924543420; 受入: R6"))
        assertTrue(text.contains("かんばん連番: 0538; 管理コード: 01335C"))
        assertTrue(text.contains("QR全文: $densoQr0140"))
        assertTrue(text.contains("QR全文: $densoQr0141"))
        assertTrue(text.contains("QR全文: $densoQr0538"))
        // KanbanQrRecord.parse accepts a Denso payload, so a missing
        // destination guard would silently print Sawai fields here.
        assertFalse(text.contains("カード番号"))
        // Delivery numbers are a Molten concept; Denso counts boxes per part.
        assertFalse(text.contains("納品番号数"))
    }

    @Test
    fun englishDensoReportUsesEnglishLabels() {
        val text = HistoryPdfContent.build(densoSession(), AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Ship-to: Denso"))
        assertTrue(text.contains("#1 860150-7722 (2 boxes)"))
        assertTrue(
            text.contains("Part number: 860150-7722; Pack quantity: 24; Instructed quantity: 72"),
        )
        assertTrue(
            text.contains(
                "Next process: D850; Instruction: C01008-45; " +
                    "Delivery date: 2026/09/08; Delivery run: S001",
            ),
        )
        assertTrue(text.contains("Management number: SWS; Item No.: 9924543330; Receiving: M6"))
        assertTrue(text.contains("Kanban serial: 0140; Management code: 1DZ50O"))
        assertTrue(text.contains("Kanban serial: 0141; Management code: 1DZB0O"))
        assertFalse(text.contains("Card number"))
        assertFalse(text.contains("Delivery numbers"))
    }

    @Test
    fun oneBlockIsEmittedPerPayloadSoLongRawValuesCannotBeDropped() {
        val rawQr = "Q".repeat(2_000)
        val rawBarcode = "B".repeat(2_000)
        val session = MatchSession(
            entries = listOf(
                MatchEntry(code = "RAW", qrPayload = rawQr, barcodePayload = rawBarcode),
            ),
        )

        val text = HistoryPdfContent.build(session).joinToString("\n") { it.text }

        assertTrue(text.contains(rawQr))
        assertTrue(text.contains(rawBarcode))
    }

    /** Two boxes of one Denso part plus a single box of a second part. */
    private fun densoSession() = MatchSession(
        startedAt = 1_700_000_000_000L,
        endedAt = 1_700_000_120_000L,
        destination = Destination.DENSO,
        entries = listOf(
            MatchEntry(
                id = "denso-1",
                code = "860150-7722",
                matchedAt = 1_700_000_001_000L,
                qrPayload = densoQr0140,
                barcodePayload = "860150-7722@1DZ50O",
                sequence = 0,
            ),
            MatchEntry(
                id = "denso-2",
                code = "860150-7722",
                matchedAt = 1_700_000_002_000L,
                qrPayload = densoQr0141,
                barcodePayload = "860150-7722@1DZB0O",
                sequence = 1,
            ),
            MatchEntry(
                id = "denso-3",
                code = "860150-7791",
                matchedAt = 1_700_000_003_000L,
                qrPayload = densoQr0538,
                barcodePayload = "860150-7791@01335C",
                sequence = 2,
            ),
        ),
    )

    /** Two boxes of one delivery number plus a second part on another slip. */
    private fun moltenSession() = MatchSession(
        startedAt = 1_700_000_000_000L,
        endedAt = 1_700_000_120_000L,
        destination = Destination.MOLTEN,
        entries = listOf(
            MatchEntry(
                id = "molten-1",
                code = "PAF1-15-422",
                matchedAt = 1_700_000_001_000L,
                qrPayload = moltenQr2,
                barcodePayload = "PAF1-15-422@0NKD3C",
                sequence = 0,
            ),
            MatchEntry(
                id = "molten-2",
                code = "PAF1-15-422",
                matchedAt = 1_700_000_002_000L,
                qrPayload = moltenQr2,
                barcodePayload = "PAF1-15-422@0NLL3C",
                sequence = 1,
            ),
            MatchEntry(
                id = "molten-3",
                code = "D10E-50-N10B",
                matchedAt = 1_700_000_003_000L,
                qrPayload = moltenQr1,
                barcodePayload = "D10E-50-N10B@0UBL00",
                sequence = 2,
            ),
        ),
    )
}
