package jp.rimtty.codematch.core.export

import jp.rimtty.codematch.core.model.AppLanguage
import jp.rimtty.codematch.core.model.MatchEntry
import jp.rimtty.codematch.core.model.MatchSession
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class HistoryPdfContentTest {
    private val qrPayload =
        "DCLP675300BCJH5281GG020000120000001200L000000000000BLBDILLU92   0*"
    private val barcodePayload = "BCJH-52-81GG@1N5X0C"

    @Test
    fun contentPreservesFirstSeenGroupsParsedFieldsManagementAndRawPayloads() {
        val session = MatchSession(
            startedAt = 1_700_000_000_000L,
            endedAt = 1_700_000_120_000L,
            name = "Morning run",
            entries = listOf(
                MatchEntry(
                    id = "one",
                    code = "BCJH-52-81GG",
                    matchedAt = 1_700_000_001_000L,
                    qrPayload = qrPayload,
                    barcodePayload = barcodePayload,
                    sequence = 0,
                ),
                MatchEntry(
                    id = "two",
                    code = "BCJH-52-81GG",
                    matchedAt = 1_700_000_002_000L,
                    qrPayload = null,
                    barcodePayload = null,
                    sequence = 1,
                ),
                MatchEntry(
                    id = "three",
                    code = "KAAA-55-D86B",
                    matchedAt = 1_700_000_003_000L,
                    qrPayload = "legacy KAAA payload",
                    barcodePayload = "KAAA-55-D86B@management-2",
                    sequence = 2,
                ),
            ),
        )

        val blocks = HistoryPdfContent.build(session, AppLanguage.JAPANESE)
        val text = blocks.joinToString("\n") { it.text }
        val firstGroup = text.indexOf("#1 BCJH-52-81GG")
        val secondGroup = text.indexOf("#2 KAAA-55-D86B")

        assertTrue(text.contains("Morning run"))
        assertTrue(text.contains("検査箱数: 3箱（品番数: 2）"))
        assertTrue(firstGroup >= 0)
        assertTrue(secondGroup > firstGroup)
        assertTrue(text.contains("納品書情報"))
        assertTrue(text.contains("カード番号: DCLP675300"))
        assertTrue(text.contains("品目番号: BCJH-52-81GG"))
        assertTrue(text.contains("管理コード: 1N5X0C"))
        assertTrue(text.contains("QR全文: $qrPayload"))
        assertTrue(text.contains("Code 128全文: $barcodePayload"))
        assertTrue(text.contains("記録なし（旧バージョンで照合）"))
        assertTrue(text.contains("management-2"))
        assertTrue(text.contains("端末内のデータから作成されています"))
    }

    @Test
    fun englishContentUsesEnglishLabelsAndIncludesEmptySessionMessage() {
        val session = MatchSession(startedAt = 0L, endedAt = 1_000L)

        val text = HistoryPdfContent.build(session, AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Match History Report"))
        assertTrue(text.contains("Boxes: 0 boxes (part numbers: 0)"))
        assertTrue(text.contains("There are no matched codes."))
        assertTrue(text.contains("Generated by CodeMatch"))
    }

    @Test
    fun englishContentInflectsBoxUnitForOneAndMany() {
        val session = MatchSession(
            endedAt = 2_000L,
            entries = listOf(
                MatchEntry(id = "one", code = "ONE"),
                MatchEntry(id = "two", code = "TWO"),
                MatchEntry(id = "three", code = "TWO"),
            ),
        )

        val text = HistoryPdfContent.build(session, AppLanguage.ENGLISH)
            .joinToString("\n") { it.text }

        assertTrue(text.contains("Boxes: 3 boxes (part numbers: 2)"))
        assertTrue(text.contains("#1 ONE (1 box)"))
        assertTrue(text.contains("#2 TWO (2 boxes)"))
    }

    @Test
    fun oneBlockIsEmittedPerPayloadSoLongRawValuesCannotBeDropped() {
        val rawQr = "Q".repeat(2_000)
        val rawBarcode = "B".repeat(2_000)
        val session = MatchSession(
            entries = listOf(
                MatchEntry(code = "RAW", qrPayload = rawQr, barcodePayload = rawBarcode),
            ),
        )

        val text = HistoryPdfContent.build(session).joinToString("\n") { it.text }

        assertTrue(text.contains(rawQr))
        assertTrue(text.contains(rawBarcode))
    }
}
