package jp.rimtty.codematch.core.export

import jp.rimtty.codematch.core.model.AppLanguage
import jp.rimtty.codematch.core.model.MatchSession
import java.text.NumberFormat
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle
import java.util.Locale

/** Localized labels shared by the PDF content builder and its callers. */
data class HistoryExportLabels(
    val reportTitle: String,
    val filePrefix: String,
    val sessionName: String,
    val start: String,
    val end: String,
    val status: String,
    val inProgress: String,
    val boxCount: String,
    val inspectionBoxCount: String,
    val partCount: String,
    val noMatches: String,
    val matchTime: String,
    val deliveryInformation: String,
    val itemNumber: String,
    val cardNumber: String,
    val suffix: String,
    val deliveryQuantity: String,
    val instructedQuantity: String,
    val factory: String,
    val warehouse: String,
    val supplyPoint: String,
    val boxRecords: String,
    val box: String,
    val managementCode: String,
    val qrFullText: String,
    val code128FullText: String,
    val legacyPayload: String,
    val generatedNote: String,
    /** Singular and plural units are kept separately for natural English. */
    val boxCountSingular: String = boxCount,
    val boxCountPlural: String = boxCount,
)

/**
 * Formatting rules used by history export.
 *
 * The formatter deliberately accepts a [ZoneId] so JVM tests can be
 * deterministic while production follows the device's current time zone.
 */
object HistoryExportTextFormatter {
    private val japaneseDateTime =
        DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM, FormatStyle.SHORT)
            .withLocale(Locale.JAPAN)
    private val englishDateTime =
        DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM, FormatStyle.SHORT)
            .withLocale(Locale.US)
    private val japaneseTime =
        DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.JAPAN)
    private val englishTime =
        DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withLocale(Locale.US)

    /** Localized PDF/UI labels. */
    fun labels(language: AppLanguage): HistoryExportLabels = when (language) {
        AppLanguage.JAPANESE -> HistoryExportLabels(
            reportTitle = "照合履歴レポート",
            filePrefix = "照合履歴",
            sessionName = "セッション名",
            start = "開始",
            end = "終了",
            status = "状態",
            inProgress = "照合中",
            boxCount = "箱",
            inspectionBoxCount = "検査箱数",
            partCount = "品番数",
            noMatches = "一致したコードはありません。",
            matchTime = "照合時刻",
            deliveryInformation = "納品書情報",
            itemNumber = "品目番号",
            cardNumber = "カード番号",
            suffix = "枝番",
            deliveryQuantity = "納入数量",
            instructedQuantity = "指示数",
            factory = "工場",
            warehouse = "受入部品庫",
            supplyPoint = "供給先",
            boxRecords = "各箱の読み取り記録",
            box = "箱",
            managementCode = "管理コード",
            qrFullText = "QR全文",
            code128FullText = "Code 128全文",
            legacyPayload = "記録なし（旧バージョンで照合）",
            generatedNote =
                "CodeMatch により生成 — このレポートは端末内のデータから作成されています。",
            boxCountSingular = "箱",
            boxCountPlural = "箱",
        )

        AppLanguage.ENGLISH -> HistoryExportLabels(
            reportTitle = "Match History Report",
            filePrefix = "MatchHistory",
            sessionName = "Session name",
            start = "Start",
            end = "End",
            status = "Status",
            inProgress = "In progress",
            boxCount = "boxes",
            inspectionBoxCount = "Boxes",
            partCount = "part numbers",
            noMatches = "There are no matched codes.",
            matchTime = "Matched",
            deliveryInformation = "Delivery information",
            itemNumber = "Item number",
            cardNumber = "Card number",
            suffix = "Suffix",
            deliveryQuantity = "Delivery quantity",
            instructedQuantity = "Instructed quantity",
            factory = "Factory",
            warehouse = "Receiving warehouse",
            supplyPoint = "Supply point",
            boxRecords = "Box scan records",
            box = "Box",
            managementCode = "Management code",
            qrFullText = "QR full text",
            code128FullText = "Code 128 full text",
            legacyPayload = "No record (matched in older app version)",
            generatedNote =
                "Generated by CodeMatch — This report was created from data stored on this device.",
            boxCountSingular = "box",
            boxCountPlural = "boxes",
        )
    }

    fun dateTime(
        epochMillis: Long,
        language: AppLanguage,
        zoneId: ZoneId = ZoneId.systemDefault(),
    ): String {
        val formatter = when (language) {
            AppLanguage.JAPANESE -> japaneseDateTime
            AppLanguage.ENGLISH -> englishDateTime
        }
        return formatter.format(Instant.ofEpochMilli(epochMillis).atZone(zoneId))
    }

    fun time(
        epochMillis: Long,
        language: AppLanguage,
        zoneId: ZoneId = ZoneId.systemDefault(),
    ): String {
        val formatter = when (language) {
            AppLanguage.JAPANESE -> japaneseTime
            AppLanguage.ENGLISH -> englishTime
        }
        return formatter.format(Instant.ofEpochMilli(epochMillis).atZone(zoneId))
    }

    fun integer(value: Int, language: AppLanguage): String =
        NumberFormat.getIntegerInstance(locale(language)).format(value)

    fun quantity(value: Double?, language: AppLanguage): String {
        if (value == null) return "-"
        val formatter = NumberFormat.getNumberInstance(locale(language)).apply {
            minimumFractionDigits = if (value % 1.0 == 0.0) 0 else 2
            maximumFractionDigits = 2
        }
        return formatter.format(value)
    }

    /**
     * Formats a box count with the language's natural singular/plural unit.
     * Japanese does not inflect the unit; English uses "box" only for one.
     */
    fun boxCount(count: Int, language: AppLanguage): String {
        val safeCount = count.coerceAtLeast(0)
        val labels = labels(language)
        val unit = if (safeCount == 1) labels.boxCountSingular else labels.boxCountPlural
        return if (language == AppLanguage.JAPANESE) {
            "${integer(safeCount, language)}$unit"
        } else {
            "${integer(safeCount, language)} $unit"
        }
    }

    /**
     * Returns a filename safe to use below cache/document-provider roots.
     * Unicode names are retained, but path separators, control characters,
     * reserved punctuation, and traversal sequences are removed.
     */
    fun fileName(
        session: MatchSession,
        language: AppLanguage,
        zoneId: ZoneId = ZoneId.systemDefault(),
    ): String {
        val labels = labels(language)
        val source = session.displayName.ifBlank {
            dateTime(session.startedAt, language, zoneId)
        }
        val safe = buildString(source.length) {
            source.forEach { character ->
                when {
                    character == '/' || character == '\\' -> append('-')
                    character == ':' -> Unit
                    character == ' ' || character == '\t' || character == '\n' -> append('_')
                    character.isISOControl() -> append('_')
                    character in RESERVED_FILENAME_CHARACTERS -> append('_')
                    else -> append(character)
                }
            }
        }.trim('_', '.', ' ')
            .replace("..", "_")
            .ifBlank { "session_${session.id.take(8)}" }

        return "${labels.filePrefix}_$safe.pdf"
    }

    private fun locale(language: AppLanguage): Locale = when (language) {
        AppLanguage.JAPANESE -> Locale.JAPAN
        AppLanguage.ENGLISH -> Locale.US
    }

    private val RESERVED_FILENAME_CHARACTERS = setOf('*', '?', '"', '<', '>', '|')
}
